version: '3.9'
services:

  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: "mongo-express"
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testDB
    volumes:
      - postgres-config:/etc/mysql
      - postgres-data:/var/lib/mysql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  mongo-data:
  postgres-data:
  postgres-config:

networks:
  default:
    name: mongodb_network